In [1]:
import numpy as np

In [2]:
#Arrays

lista = [1, 2, 3, 4, 5, 6]

array = np.array(lista)

In [4]:
print(type(lista))
print(type(array))

<class 'list'>
<class 'numpy.ndarray'>


In [5]:
arr_zeros = np.zeros(10)

print(arr_zeros)

[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]


In [6]:
array[0] = 9
print(array)

[9 2 3 4 5 6]


In [7]:
#Matrizes
matrizes_zeros = np.zeros((5,3))
print(matrizes_zeros)

[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]


In [8]:
#Notas alunos

listaDeNotas = [9.8, 5.6, 7.8, 9.1, 6,5]

notas = np.array(listaDeNotas)

In [9]:
print("Maximo", notas.max())
print("Minimo", notas.min())
print("Desvio Padrao", notas.std())
print("Media", notas.mean())
print("Posicao Menor", notas.argmin())

Maximo 9.8
Minimo 5.0
Desvio Padrao 1.805931584775262
Media 7.216666666666666
Posicao Menor 5


In [34]:
#Peça pro usuario digitar 9 números e faça algumas operações

listaNotas = []

for i in range(9):
    listaNotas.append(int(input("Escreva 1 número: ")))

Escreva 1 número:  1
Escreva 1 número:  2
Escreva 1 número:  3
Escreva 1 número:  4
Escreva 1 número:  5
Escreva 1 número:  6
Escreva 1 número:  7
Escreva 1 número:  8
Escreva 1 número:  9


In [35]:
print(listaNotas)

[1, 2, 3, 4, 5, 6, 7, 8, 9]


In [36]:
notasAlunos = np.array(listaNotas)

#notasAlunosInteiro = notasAlunos.astype(int)
#print(notasAlunosInteiro)

In [37]:
print("Maior nota: ", notasAlunos.max())
print("Menor nota:", notasAlunos.min())
print("Desvio Padrao", notasAlunos.std())
print("Media", notasAlunos.mean())
print("Posicao Menor", notasAlunos.argmin())
print("Posicao Maior", notasAlunos.argmax())

Maior nota:  9
Menor nota: 1
Desvio Padrao 2.581988897471611
Media 5.0
Posicao Menor 0
Posicao Maior 8
